IMAGE_SIZE:
  - 448
  - 448

S: 7
B: 2
C: 20

VOC_DETECTION_CATEGORIES:
  # - "__background__"
  - "aeroplane"
  - "bicycle"
  - "bird"
  - "boat"
  - "bottle"
  - "bus"
  - "car"
  - "cat"
  - "chair"
  - "cow"
  - "diningtable"
  - "dog"
  - "horse"
  - "motorbike"
  - "person"
  - "pottedplant"
  - "sheep"
  - "sofa"
  - "train"
  - "tvmonitor"

L_coord: 3.0
L_obj: 1.0
L_noobj: 1.0
L_class: 1.0

Rescore: True

MODEL: "resnet50"

BATCH_SIZE: 8
NUM_EPOCHS: 135
ACCUMULATE_GRAD_BATCHES: 8
NUM_WORKERS: 4

LEARNING_RATE: 0.002
WEIGHT_DECAY: 0.0005
